#ifndef EVENT_BUS_CONFIG
#define EVENT_BUS_CONFIG

#include <FreeRTOS.h>

#define EVENT_BUS_RTOS_PRIORITY (configMAX_PRIORITIES - 2)

#define EVENT_BUS_POOL_SM_SZ 32
#define EVENT_BUS_POOL_SM_LN 128

#define EVENT_BUS_POOL_LG_SZ 256
#define EVENT_BUS_POOL_LG_LN 64

#define EVENT_BUS_MAX_CMD_QUEUE 32
#define EVENT_BUS_MASK_WIDTH 3

#define EVENT_BUS_DEBUG_QUEUE_FULL(name) configASSERT(0)
#define EVENT_BUS_USE_TASK_NOTIFICATION_INDEX 1

#endif